apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: stress
  name: stress
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-deployment
  namespace: stress
  labels:
    app: stress
spec:
  #replicas: 1
  selector:
    matchLabels:
      app: stress
  template:
    metadata:
      labels:
        app: stress
    spec:
      containers:
      - name: stress-container
        image: progrium/stress
        args: ["--cpu", "2", "--timeout", "600s"]
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: stress-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: stress-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 20
